version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: node --version
      - run: "npm install --save-dev jest"
  
      - run: "npm run test"
  test:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: "npm run lint"
  analyze:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run: "npm audit"
workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build 
      - analyze:
          requires:
            - test