version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run: "npm run test"
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: "npm run lint"
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - run: "npm audit"
workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build 
      - analyze:
          requires:
            - test